apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: {{ .Values.namespace }}
  labels:
    backstage.io/kubernetes-id: {{ .Values.backstage.kubernetesId }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.username }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}