# kubernetes/postgres-service.yaml
apiVersion: {{ .Values.service.apiVersion }}
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    backstage.io/kubernetes-id: {{ .Values.backstage.kubernetesId }}
spec:
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    - port: {{ .Values.service.port }}